### ISSUE TITLE
Save NeuralNet State

### ISSUE THREAD

**Issue by mschultheiss83** [Code-Bullet/AsteroidsAI#1]
Hi there, 
first of all i like you videos and i share them...

Can you point me, how to save the NeuralNet State in Processing?

i'm running it now for a while GEN: 80 / Best Score: > 530, and i  want to save the state as you did with the snakes to combine them later...

**EDIT:** Now i see a TableToNet and NetToTable function, would this work with Asteroids brain?
**EDIT 2:** Now i see the savePlayer / loadPlayer functions

**Comment by marshalhayes** [comment]
@mschultheiss83 Did you figure out a way to periodically save the neural net's state?

**Comment by mschultheiss83** [comment]
Yes @marshalhayes. Every time we have a new best player
